version: '3.8'

services:
  backend:
    image: aventus_sre_challenge:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres-db:5432/aventus"
    restart: always

  postgres-db:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aventus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "aventus"]
      interval: 5s
      timeout: 5s
      retries: 3

