apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
