name: Build Docker Image and push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Checkout the repository code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Login to Docker Hub to push the built image
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      # Build the Docker image
      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t galactica/aventus_sre_challenge:latest .

      # Push the Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: galactica/aventus_sre_challenge:latest
